[package]
name = "listingsdb-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.61.0"
cc = "1.0.74"

[dependencies]
serde = { version = "1.0.147", features = ["derive"] }